#Python CircleCI 2.0 configuration file
version: 2
executor:
  name: common/node
  feature: '-browsers'
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/devops
    steps:
    #1 Obtener el repositorio de GitHub.
      - checkout
      #2 Crear un entorno virtual e instalar las dependecias.
      - run:
          name: install dependencies
          command: |
            npm i
      #3 Ejecutar el software de convenciones de codificación más el tester.
      - run:
          name: run tests
          command: |
            CHROME_BIN=/usr/bin/google-chrome karma start --single-run
            npm run test
