#Python CircleCI 2.0 configuration file
version: 2
executor:
  name: common/node:16
  feature: '-browsers'
jobs:
  build:
    docker:
      - image: circleci/node:lts
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    working_directory: ~/devops
    steps:
    #1 Obtener el repositorio de GitHub.
      - checkout
      #2 Crear un entorno virtual e instalar las dependecias.
      - run:
          name: install dependencies
          command: |
            npm i
            nvm use --lts
      #3 Ejecutar el software de convenciones de codificación más el tester.
      - run:
          name: run tests
          command: |            
            npm run test
